# Workflow name displayed in GitHub Actions tab
name: Build Flatpak

# Define when this workflow should run.
on:
  push:
    branches:
      - main # Or 'master' if that's your main branch name

# Define the jobs that make up this workflow
jobs:
  build_flatpak:
    # Name of the job
    name: Build Flatpak
    # Operating system the job will run on
    runs-on: ubuntu-latest

    steps:
      # --- Step 1: Checkout the source code ---
      - name: Checkout code
        uses: actions/checkout@v4

      # --- Step 2: Install Flatpak and Flatpak Builder ---
      - name: Install Flatpak and Builder
        run: |
          sudo apt-get update
          sudo apt-get install -y flatpak flatpak-builder

      # --- Step 3: Install Flatpak SDK and Runtime --- # <--- ADDED THIS STEP
      # flatpak-builder requires the SDK and Runtime to be installed first.
      - name: Install Flatpak SDK and Runtime
        run: |
          flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
          flatpak install -y flathub org.gnome.Sdk//46
          flatpak install -y flathub org.gnome.Platform//46

      # --- Step 4: Verify Flatpak Files Existence (Optional but good check) ---
      - name: Verify Flatpak files existence
        run: |
          ls com.drl990114.markflowy.yaml
          ls com.drl990114.markflowy.appdata.xml

      # --- Step 5: Build the Flatpak application ---
      # Run flatpak-builder using your manifest file.
      - name: Run Flatpak Builder
        run: |
          flatpak-builder --force-clean --repo=repo build-dir com.drl990114.markflowy.yaml
        # If this step fails, check the logs in the GitHub Actions UI.

      # --- Step 6: Archive and upload the built repository ---
      - name: Upload Flatpak repository artifact
        uses: actions/upload-artifact@v4
        with:
          name: flatpak-repo
          path: repo
          # retention-days: 7

      # --- Step 7: (Optional) Create a .flatpak file for easy installation ---
      - name: Create and upload Flatpak bundle
        # Only run this step if the build was successful
        if: success()
        run: |
          flatpak build-bundle repo markflowy.flatpak com.drl990114.markflowy
          ls markflowy.flatpak

      - name: Upload Flatpak bundle artifact
        if: success() # Only upload if the bundle was created
        uses: actions/upload-artifact@v4
        with:
          name: markflowy-flatpak-bundle
          path: markflowy.flatpak
          # retention-days: 7
