# Workflow name displayed in GitHub Actions tab
name: Build Flatpak

# Define when this workflow should run.
# We'll trigger it on pushes to the main branch.
on:
  push:
    branches:
      - main # Or 'master' if that's your main branch name

# Define the jobs that make up this workflow
jobs:# Workflow name displayed in GitHub Actions tab
name: Build Flatpak

# Define when this workflow should run.
# We'll trigger it on pushes to the main branch.
on:
  push:
    branches:
      - main # Or 'master' if that's your main branch name

# Define the jobs that make up this workflow
jobs:
  build_flatpak:
    # Name of the job
    name: Build Flatpak
    # Operating system the job will run on
    runs-on: ubuntu-latest

    steps:
      # --- Step 1: Checkout the source code ---
      - name: Checkout code
        uses: actions/checkout@v4

      # --- Step 2: Install Flatpak and Flatpak Builder ---
      - name: Install Flatpak and Builder
        run: |
          sudo apt-get update
          sudo apt-get install -y flatpak flatpak-builder

      # --- Step 3: Install Flatpak SDK and Runtime --- # <-- ADDED THIS STEP
      - name: Install Flatpak SDK and Runtime
        run: |
          flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
          # Use 'sudo' because flatpak install needs root when run system-wide in CI
          sudo flatpak install -y flathub org.gnome.Sdk//46
          sudo flatpak install -y flathub org.gnome.Platform//46

      # --- Step 4: Prepare Flatpak Files --- # Renumbered
      # Assuming com.drl990114.markflowy.yaml and com.drl990114.markflowy.appdata.xml are in the repo root.
      - name: Verify Flatpak files existence
        run: |
          ls com.drl990114.markflowy.yaml
          ls com.drl990114.markflowy.appdata.xml
        # This step just checks if the files are where expected after checkout.

      # --- Step 5: Build the Flatpak application --- # Renumbered
      - name: Run Flatpak Builder
        run: |
          # Run flatpak-builder using your manifest file.
          # --build-dir: directory for build artifacts
          # --repo: directory where the resulting flatpak repository will be created
          # --force-clean: cleans the build directory before starting
          flatpak-builder --force-clean --repo=repo build-dir com.drl990114.markflowy.yaml
        # If this step fails, check the logs in the GitHub Actions UI.

      # --- Step 6: Archive and upload the built repository --- # Renumbered
      - name: Upload Flatpak repository artifact
        uses: actions/upload-artifact@v4
        with:
          name: flatpak-repo
          path: repo
          # Optional: configure retention days if needed
          # retention-days: 7

      # --- Step 7: (Optional) Create a .flatpak file for easy installation --- # Renumbered
      - name: Create and upload Flatpak bundle
        # Only run this step if the build was successful
        if: success()
        run: |
          # Build the bundle from the repository
          flatpak build-bundle repo markflowy.flatpak com.drl990114.markflowy
          # Check if the bundle was created
          ls markflowy.flatpak

      - name: Upload Flatpak bundle artifact
        if: success() # Only upload if the bundle was created
        uses: actions/upload-artifact@v4
        with:
          name: markflowy-flatpak-bundle
          path: markflowy.flatpak
          # Optional: configure retention days if needed
          # retention-days: 7
  build_flatpak:
    # Name of the job
    name: Build Flatpak
    # Operating system the job will run on
    runs-on: ubuntu-latest

    steps:
      # --- Step 1: Checkout the source code ---
      - name: Checkout code
        uses: actions/checkout@v4

      # --- Step 2: Install Flatpak and Flatpak Builder ---
      # These tools are needed on the GitHub Actions runner itself
      - name: Install Flatpak and Builder
        run: |
          sudo apt-get update
          sudo apt-get install -y flatpak flatpak-builder

      # --- Step 3: Prepare Flatpak Files ---
      # Ensure the manifest and appdata files are in the correct location.
      # Assuming com.drl990114.markflowy.yaml and com.drl990114.markflowy.appdata.xml are in the repo root.
      - name: Verify Flatpak files existence
        run: |
          ls com.drl990114.markflowy.yaml
          ls com.drl990114.markflowy.appdata.xml
        # This step just checks if the files are where expected after checkout.

      # --- Step 4: Build the Flatpak application ---
      # Run flatpak-builder using your manifest file.
      # --build-dir: directory for build artifacts
      # --repo: directory where the resulting flatpak repository will be created
      # --force-clean: cleans the build directory before starting
      # Flatpak-builder will download the necessary SDK/Runtime (GNOME 46) itself.
      - name: Run Flatpak Builder
        run: |
          flatpak-builder --force-clean --repo=repo build-dir com.drl990114.markflowy.yaml
        # If this step fails, check the logs in the GitHub Actions UI.

      # --- Step 5: Archive and upload the built repository ---
      # This makes the resulting 'repo' directory available for download from the GitHub Actions run page.
      - name: Upload Flatpak repository artifact
        uses: actions/upload-artifact@v4
        with:
          name: flatpak-repo
          path: repo
          # Optional: configure retention days if needed
          # retention-days: 7

      # --- Step 6: (Optional) Create a .flatpak file for easy installation ---
      # An alternative to exporting a repo is creating a single .flatpak file.
      # This might be easier for users to install directly.
      # Requires flatpak version >= 1.0.
      - name: Create and upload Flatpak bundle
        # Only run this step if the build was successful
        if: success()
        run: |
          # Build the bundle from the repository
          flatpak build-bundle repo markflowy.flatpak com.drl990114.markflowy
          # Check if the bundle was created
          ls markflowy.flatpak

      - name: Upload Flatpak bundle artifact
        if: success() # Only upload if the bundle was created
        uses: actions/upload-artifact@v4
        with:
          name: markflowy-flatpak-bundle
          path: markflowy.flatpak
          # Optional: configure retention days if needed
          # retention-days: 7
